### ISSUE TITLE
 chocopkgup.exe.config gets overwritten on every update

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey-package-updater#11]
chocopkgup.exe.config in ChocolateyBinRoot/ChocolateyPackageUpdater gets overwritten on every update so that every time the "PackagesFolder" key changes back to default, breaking ketarin-updates.

**Comment by ferventcoder** [comment]
As noted in #650 - this is an issue with the framework, not something packages should handle

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/choco/issues/110

**Comment by TomOne** [comment]
> As noted in #650 - this is an issue with the framework, not something packages should handle

I don’t think so. This is really an issue of chocopkgup, see https://github.com/chocolatey/chocolatey-package-updater/issues/17#issuecomment-75840515
