### ISSUE TITLE
Allow version to have pre-release characteristics e.g. -beta1

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey-package-updater#12]

**Comment by dtgm** [comment]
Just ran into this issue.  Package folder gets created with char version name, but today's date gets added as string of version.  It appears this forced manipulation is an attempt to follow nuspec versioning specs, however oddly the hyphen is not being modified.  It looks like the folder gets created before modifying the version string.

Also should allow 
-alpha2
-nightly3

adgellida also had this issue https://groups.google.com/forum/#!topic/chocolatey/YYJ9SpkLpKU
You discussed it with him at https://groups.google.com/d/msg/chocolatey/b5hQqbaUDbQ/6WyWXHkUb3IJ

He didn't post a fix so the only workaround I can see until this is corrected is misusing another variable passed by chocopkgup.

**Comment by ferventcoder** [comment]
Yep, took me awhile to understand what adgellida meant. I think we'll want
a Boolean switch so the version is left alone if beta.

On Sunday, January 18, 2015, dtgm <notifications@github.com> wrote:

> Just ran into this issue. Package folder gets created with char version
> name, but today's date gets added as string of version. It appears this
> forced manipulation is an attempt to follow nuspec versioning specs,
> however oddly the hyphen is not being modified. It looks like the folder
> gets created before modifying the version string.
>
> Also should allow
> -alpha2
> -nightly3
>
> adgellida also had this issue
> https://groups.google.com/forum/#!topic/chocolatey/YYJ9SpkLpKU
> You discussed it with him at
> https://groups.google.com/d/msg/chocolatey/b5hQqbaUDbQ/6WyWXHkUb3IJ
>
> He didn't post a fix so the only workaround I can see until this is
> corrected is misusing another variable passed by chocopkgup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/chocolatey-package-updater/issues/12#issuecomment-70441531>
> .
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Similar to #18.
