### ISSUE TITLE
Sync this repository with the actual release on Chocolatey.org

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-package-updater#13]
Some files in this repo are outdated. I think it is important to have them synchronized with the actual release on Chocolatey.org, otherwise the contributions to this repo will never be applied in a release.

**Comment by ferventcoder** [comment]
Doesn't this fall under the other issue?

**Comment by ferventcoder** [comment]
https://github.com/chocolatey/chocolatey-package-updater/issues/3

**Comment by TomOne** [comment]
No, the other issue was just about adding the files for the first time.

They need to be kept in sync with the actual release on Chocolatey.org. The nuspec in this repo still shows the outdated version. Not optimal.

**Comment by ferventcoder** [comment]
The nuspec will always show an outdated version. The version is NOT updated in the nuspec. It's updated at build time. However, the release notes ARE out of sync and should follow.

**Comment by TomOne** [comment]
How about including the built nuspec and commit it into the repo? Should be easily possible with a little script.

**Comment by ferventcoder** [comment]
Well I can't do soft links. Let's try hard links

**Comment by ferventcoder** [comment]
There you go. Note [setup_links.ps1](https://github.com/chocolatey/chocolatey-package-updater/blob/master/setup_links.ps1) file and you may start to understand why I was so hesitant. Nothing is set as clean as you would want it over in the other. The build automation puts it all together.

**Comment by ferventcoder** [comment]
Now I have fulfilled a request, would you mind taking a look at the ruby packages that need to be updated on chocolatey.org to alleviate the CVEs? https://chocolatey.org/packages/ruby/2.0.0.59800 and https://chocolatey.org/packages/ruby/1.9.3.55100
