### ISSUE TITLE
chocopkgup should support prereleases

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/chocolatey-package-updater#18]
At the moment it is hard to create automatic prerelease packages. I personally found no easy way.

related:
https://groups.google.com/forum/#!topic/chocolatey/b5hQqbaUDbQ

**Comment by ferventcoder** [comment]
Done

**Comment by ferventcoder** [comment]
Pass in the version with `-` and it will work appropriately. Alternatively, use `--beta` and it will not attempt to normalize the version.
