### ISSUE TITLE
License for 0.6.5 has expired

### ISSUE THREAD

**Issue by dtgm** [chocolatey/chocolatey-package-updater#20]
It's been 6 months.

https://github.com/chocolatey/chocolatey-package-updater/issues/9

**Comment by ferventcoder** [comment]
https://chocolatey.org/packages/ChocolateyPackageUpdater/0.6.6.0

**Comment by ferventcoder** [comment]
@dtgm would you mind taking a look at that one?

**Comment by dtgm** [comment]
@ferventcoder approved

**Comment by ferventcoder** [comment]
Thanks!
