### ISSUE TITLE
Package updater replaces {{DownloadUrl}} with empty string

### ISSUE THREAD

**Issue by dhilgarth** [chocolatey/chocolatey-package-updater#22]
In one of my packages, the package updater simply replaces `{{DownloadUrl}}` with an empty string.  
As far as I can tell, I am doing everything correctly. Unfortunately, I can't reliably reproduce the issue in the command line, but I *was* able to reproduce it. But with the same parameters it works at other times, so I don't really have a reproduction.

I created a short video showing my Ketarin configuration and the result: http://screencast.com/t/595VfKPaam9

**Comment by ferventcoder** [comment]
I watched the video and noticed the following:

* In Settings -> Commands you used after updating an application. No idea if that works. It should work just fine though.
* I'm wondering why you decided to create a downloadurl. You should try a different local variable in case it is conflicting with something built into Ketarin.

For reference:
![image](https://cloud.githubusercontent.com/assets/63502/10032686/3e1c95c8-614a-11e5-9737-99ff1f3edd09.png)
![image](https://cloud.githubusercontent.com/assets/63502/10032692/47248ee6-614a-11e5-8df0-e8a69f9cf48e.png)


I'm wondering if you would click on Log (`Ctrl+L` or View -> Show log) and show that as part of it. Then you can see how chocopkgup was actually called.

**Comment by ferventcoder** [comment]
I'm wondering if you would click on Log (`Ctrl+L` or View -> Show log) and show that as part of it. Then you can see how chocopkgup was actually called.

**Comment by dhilgarth** [comment]
Thanks for your comment. You might remember the balsamiqmockups3 package where we decided to include the ZIP file? That's the reason I am using "after download", because otherwise the package is being built BEFORE the file has actually been downloaded. The downloadUrl variable is working just fine, I am using it in all of my packages.

**Comment by dhilgarth** [comment]
Thanks a lot for the hint with Ctrl+L. I now found the reason. Because the version numbers from Room Arranger are all over the place with regards to the parts used (v8, v7.5, v7.6.9), I am doing a little processing inside Ketarin using some temporary variables. One of those variables had a newline in it. Ketarin passed that to the command line, resulting in two commands being executed:
1. The first part of the defined command until right after the version number
2. All the parameters thereafter.

You can see me realizing and fixing it here: http://screencast.com/t/fPY2AxBlz8e0

**Comment by ferventcoder** [comment]
Awesome. :)
