### ISSUE TITLE
Command line override which allows chocopkgup to deploy packages from more than one repo. 

### ISSUE THREAD

**Issue by dsudduth** [chocolatey/chocolatey-package-updater#23]
In instances where a user or team may have multiple repositories, it may be helpful to be able to designate which repo a package will be deployed to.  For example, our teams are using Artifactory to manage repositories.  We have some repos dedicated to very specific features, or tools and others which are more general in nature.  As an addition to the updater, it would be great if we could somehow define where each package should be deployed once generated and compressed.

**Comment by ferventcoder** [comment]
Thanks for adding!

**Comment by ferventcoder** [comment]
I believe this is there? I see `--pf` or `--packagesfolder` - can you verify it works?
