### ISSUE TITLE
[Enhancement] Option to only keep the latest files for each package in the _output folder

### ISSUE THREAD

**Issue by TomOne** [chocolatey/chocolatey-package-updater#5]
Currently the package updater creates a folder for each package version in _output. When the _output folder is checked into a Git repository, this is unnecessary and only results in a more bloated repository. Git is already a versioning system, so it would be straightforward to version the package versions in the _output folder with Git.

Therefore an option to do that and to make an automatic commit after each package update would be nice.

**Comment by ferventcoder** [comment]
Didn't catch this one yet.

**Comment by ferventcoder** [comment]
And done for 0.6.9.

The config value is `LatestPackageVersionOnly` defaulted to false for an existing install.
