### ISSUE TITLE
Support for passing {{checksum}} variable

### ISSUE THREAD

**Issue by dtgm** [chocolatey/chocolatey-package-updater#7]
Please add support for passing {{checksum}} with ChocoPkgUp.exe.

See: https://github.com/chocolatey/chocolatey/issues/427#issuecomment-60740928

**Comment by ferventcoder** [comment]
Checksum and Checksumx64

**Comment by ferventcoder** [comment]
`/c=` or `/checksum=`
`/c64` or `/checksumx64`

**Comment by ferventcoder** [comment]
Done with 0.6.4.
