### ISSUE TITLE
Package pushed to Chocolatey by ketarin while /disablepush has been specified

### ISSUE THREAD

**Issue by 030** [chocolatey/chocolatey-package-updater#8]
# Expected outcome

The package will not be pushed if /disablepush is specified:

### Execute the following command after downloading
    chocopkgup /p {appname} /v {version} /u "{preupdate-url}" /u64 "{url64}" /pp "{file}" /disablepush

# Current outcome

The package is pushed

**Comment by ferventcoder** [comment]
What does the log say?

**Comment by ferventcoder** [comment]
This has been pretty stale, so I'm going to close it for now. If you are still seeing this issue, please comment or open a new issue and point to this one. Thanks!
